
-- INSERT INTO TRADUCCIONES  (TEXTO, IDIDIOMA, IDTERMINO) VALUES ('Patr'||CHR(38)||'oacute; de Qu'||CHR(38)||'iacute;mica',1,1525);	
-- INSERT INTO TRADUCCIONES  (TEXTO, IDIDIOMA, IDTERMINO) VALUES ('Chemistry pattern',2,1525);	
-- INSERT INTO TRADUCCIONES  (TEXTO, IDIDIOMA, IDTERMINO) VALUES ('Chemiemuster',3,1525);	
-- INSERT INTO TRADUCCIONES  (TEXTO, IDIDIOMA, IDTERMINO) VALUES ('Mod'||CHR(38)||'egrave;le de Chimie',4,1525);

INSERT INTO TIPOS_PATRONES ( IDTERMINO,NOMBRE,IDPATRON, CLASE ) 
VALUES ( 1525,'Patron Quimica',9,'siette.quimica.PatronQuimica'  ) ; 
